Clientes/Models/COMPROMISO.cs
namespace Clientes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("EMPRESARIALES.COMPROMISO")]
    public partial class COMPROMISO
    {
        [Key]
        public int ID { get; set; }

        public int? CONTACTO_ID { get; set; }

        [Column("COMPROMISO", TypeName = "text")]
        //Crear textarea
        [DataType(DataType.MultilineText)]
        [Display(Name = "Compromiso")]
        [Required]
        public string COMPROMISO1 { get; set; }

        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha compromiso")]
        [Required]
        public DateTime? FECHA_COMPROMISO { get; set; }

        public virtual CONTACTO CONTACTO { get; set; }
    }
}

Clientes/Models/CONTACTO.cs
namespace Clientes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("EMPRESARIALES.CONTACTO")]
    public partial class CONTACTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTACTO()
        {
            COMPROMISOes = new HashSet<COMPROMISO>();
            PROXIMO_CONTACTO = new HashSet<PROXIMO_CONTACTO>();
        }

        [Key]
        public int ID { get; set; }

        public int CONOCIMIENTO_ID { get; set; }

        [StringLength(100)]
        public string NOMBRE_CONTACTO { get; set; }

        [StringLength(50)]
        public string TIPO_CONTACTO { get; set; }

        //Crear textarea
        [DataType(DataType.MultilineText)]
        [Column(TypeName = "text")]
        public string COMENTARIO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPROMISO> COMPROMISOes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROXIMO_CONTACTO> PROXIMO_CONTACTO { get; set; }


        public DateTime FECHA_CONTACTO { get; set; }
    }
}

Clientes/Controllers/ContactosController.cs
using Clientes.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Clientes.Controllers
{
    public class ContactosController : Controller
    {
        private EmpresarialesModel db = new EmpresarialesModel();
        // GET: Contactos
        //[OutputCache(Duration = 300, VaryByParam = "none")] //cached for 300 seconds 
        public ActionResult Index()
        {
            return View(db.CONTACTOes.ToList());
        }



        //Calendario
        //[OutputCache(Duration = 300, VaryByParam = "none")] //cached for 300 seconds 
        public ActionResult Inicio(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                ViewBag.vend = id;
            }

            ViewData["ejecutivos"] = new SelectList(db.COUSUARIOS.ToList().Where(x => x.ACTIVO = true && x.PERFIL != 1), "VENDEDOR", "NOMBRE");
            return View();
        }

        public JsonResult Eventos(string id,DateTime start, DateTime end)
        {
            //var actividades = db.CONTACTOes.Where(x => x.FECHA_COMPROMISO != null && (x.FECHA_COMPROMISO >= start && x.FECHA_COMPROMISO <= end)).ToList();
            var compromisos = (from cn in db.CONOCIMIENTO
                               join c in db.CONTACTOes
                               on cn.ID equals c.CONOCIMIENTO_ID
                               join cp in db.COMPROMISOes
                               on c.ID equals cp.CONTACTO_ID
                               select new
                               {
                                   cp.ID,
                                   cp.FECHA_COMPROMISO,
                                   cn.NOMBRE_COMERCIAL,
                                   cp.COMPROMISO1,
                                   cn.EJECUTIVO_FONIX,
                               }).ToList();


            var proximo = (from cn in db.CONOCIMIENTO
                               join c in db.CONTACTOes
                               on cn.ID equals c.CONOCIMIENTO_ID
                               join cp in db.PROXIMO_CONTACTO
                               on c.ID equals cp.CONTACTO_ID
                               select new
                               {
                                   cp.ID,
                                   cp.MOTIVO_PROXIMO_CONTACTO,
                                   cn.NOMBRE_COMERCIAL,
                                   cp.FECHA_PROXIMO_CONTACTO,
                                   cp.HORA_PROXIMO_CONTACTO,
                                   cn.EJECUTIVO_FONIX
                               }).ToList();


            if (!String.IsNullOrEmpty(id))
            {
                compromisos = compromisos.Where(x => x.EJECUTIVO_FONIX == id).ToList();
                proximo = proximo.Where(x => x.EJECUTIVO_FONIX == id).ToList();
            }

            List<Events> eventos = new List<Events>();
            foreach (var item in compromisos)
            {
                Events evento = new Events();
                evento.id = item.ID;
                evento.start = Convert.ToDateTime(item.FECHA_COMPROMISO).ToString("s", System.Globalization.CultureInfo.InvariantCulture);

                var query = db.COMPROMISOes.Find(item.ID);
                var contacto = db.CONTACTOes.Find(query.CONTACTO_ID);
                var max = db.CONTACTOes.Where(x => x.CONOCIMIENTO_ID == contacto.CONOCIMIENTO_ID).Max(x=>x.FECHA_CONTACTO);

                evento.estatus = max == item.FECHA_COMPROMISO ? "Cumplido" : item.FECHA_COMPROMISO > max && item.FECHA_COMPROMISO > DateTime.Now ? "Vigente" : "Incumplido";

                evento.color = "#7f181b";
                //evento.end = item.FECHA_COMPROMISO.ToString("o");
                //evento.title = item.Nombre + " " + item.Descripcion;
                evento.title = "Compromiso-" + item.NOMBRE_COMERCIAL + "-" + item.COMPROMISO1 + "::" + evento.estatus;
                evento.ejecutivo = item.EJECUTIVO_FONIX;
                evento.tipo = "C";
                eventos.Add(evento);
            }

            foreach (var item in proximo)
            {
                Events evento = new Events();
                evento.id = item.ID;
                evento.start = Convert.ToDateTime(item.FECHA_PROXIMO_CONTACTO).ToString("s", System.Globalization.CultureInfo.InvariantCulture);


                var query = db.PROXIMO_CONTACTO.Find(item.ID);
                var contacto = db.CONTACTOes.Find(query.CONTACTO_ID);
                var max = db.CONTACTOes.Where(x => x.CONOCIMIENTO_ID == contacto.CONOCIMIENTO_ID).Max(x => x.FECHA_CONTACTO);


                evento.estatus = Convert.ToDateTime(max).ToShortDateString() == Convert.ToDateTime(item.FECHA_PROXIMO_CONTACTO).ToShortDateString() ? "Cumplido" : (item.FECHA_PROXIMO_CONTACTO > max  && item.FECHA_PROXIMO_CONTACTO > DateTime.Now) || (Convert.ToDateTime(item.FECHA_PROXIMO_CONTACTO).ToShortDateString() == DateTime.Now.ToShortDateString())  ? "Vigente" : "Incumplido";

                evento.color = "#0099e5";
                evento.title = "ProximoContacto-" + item.NOMBRE_COMERCIAL + "-" + item.MOTIVO_PROXIMO_CONTACTO + "::" + evento.estatus;
                evento.ejecutivo = item.EJECUTIVO_FONIX;
                evento.tipo = "P";
                eventos.Add(evento);
            }

            return Json(eventos, JsonRequestBehavior.AllowGet);
        }







        //[OutputCache(Duration = 300, VaryByParam = "none")] //cached for 300 seconds 
        public ActionResult Detail(int? id)
        {
            //return View(db.CONTACTOes.Find(id));
            ViewBag.CL = id;
            var cliente = db.CONOCIMIENTO.Find(id);
            ViewBag.Cliente = cliente.RAZON_SOCIAL;
            var query = (from c in db.CONTACTOes
                         //join p in db.PROXIMO_CONTACTO
                         //on c.ID equals p.CONTACTO_ID
                         join cp in db.COMPROMISOes
                         on c.ID equals cp.CONTACTO_ID
                         where c.CONOCIMIENTO_ID == id
                         select new
                         {
                             c.COMENTARIO,
                             c.CONOCIMIENTO_ID,
                             c.FECHA_CONTACTO,
                             c.ID,
                             c.NOMBRE_CONTACTO,
                             c.TIPO_CONTACTO,
                             //p.MOTIVO_PROXIMO_CONTACTO,
                             //p.FECHA_PROXIMO_CONTACTO,
                             //p.HORA_PROXIMO_CONTACTO,
                             cp.COMPROMISO1,
                             cp.FECHA_COMPROMISO
                         }).ToList();


            var query2 = (from c in db.CONTACTOes
                          join p in db.PROXIMO_CONTACTO
                          on c.ID equals p.CONTACTO_ID
                         //join cp in db.COMPROMISOes
                         //on c.ID equals cp.CONTACTO_ID
                         where c.CONOCIMIENTO_ID == id
                         select new
                         {
                             c.COMENTARIO,
                             c.CONOCIMIENTO_ID,
                             c.FECHA_CONTACTO,
                             c.ID,
                             c.NOMBRE_CONTACTO,
                             c.TIPO_CONTACTO,
                             p.MOTIVO_PROXIMO_CONTACTO,
                             p.FECHA_PROXIMO_CONTACTO,
                             p.HORA_PROXIMO_CONTACTO,
                             //cp.COMPROMISO1,
                             //cp.FECHA_COMPROMISO
                         }).ToList();


            List<ContactoModelView> contactos = new List<ContactoModelView>();
            foreach (var i in query)
            {
                ContactoModelView cont = new ContactoModelView();
                cont.COMENTARIO = i.COMENTARIO;
                //cont.MOTIVO_PROXIMO_CONTACTO = i.MOTIVO_PROXIMO_CONTACTO;
                cont.CONOCIMIENTO_ID = i.CONOCIMIENTO_ID;
                //cont.FECHA_PROXIMO_CONTACTO = i.FECHA_PROXIMO_CONTACTO;
                //cont.HORA_PROXIMO_CONTACTO = i.HORA_PROXIMO_CONTACTO;
                cont.FECHA_CONTACTO = i.FECHA_CONTACTO;
                cont.NOMBRE_CONTACTO = i.NOMBRE_CONTACTO;
                cont.TIPO_CONTACTO = i.TIPO_CONTACTO;
                cont.COMPROMISO = i.COMPROMISO1;
                cont.FECHA_COMPROMISO = i.FECHA_COMPROMISO;
                contactos.Add(cont);
            }


            foreach (var i in query2)
            {
                ContactoModelView cont = new ContactoModelView();
                cont.COMENTARIO = i.COMENTARIO;
                cont.MOTIVO_PROXIMO_CONTACTO = i.MOTIVO_PROXIMO_CONTACTO;
                cont.CONOCIMIENTO_ID = i.CONOCIMIENTO_ID;
                cont.FECHA_PROXIMO_CONTACTO = Convert.ToDateTime(i.FECHA_PROXIMO_CONTACTO).ToShortTimeString();
                cont.HORA_PROXIMO_CONTACTO = i.HORA_PROXIMO_CONTACTO;
                cont.FECHA_CONTACTO = i.FECHA_CONTACTO;
                cont.NOMBRE_CONTACTO = i.NOMBRE_CONTACTO;
                cont.TIPO_CONTACTO = i.TIPO_CONTACTO;
                //cont.COMPROMISO = i.COMPROMISO1;
                //cont.FECHA_COMPROMISO = i.FECHA_COMPROMISO;
                contactos.Add(cont);
            }


            return View(contactos);
        }

        //[OutputCache(Duration = 300, VaryByParam = "none")] //cached for 300 seconds 
        public ActionResult Compromisos(int id)
        {
            var cliente = db.CONOCIMIENTO.Find(id);
            ViewBag.Cliente = cliente.RAZON_SOCIAL;
            var query = (from c in db.CONTACTOes
                        join p in db.COMPROMISOes
                        on c.ID equals p.CONTACTO_ID
                        where c.CONOCIMIENTO_ID==id
                        select new {
                            c.COMENTARIO,
                            c.CONOCIMIENTO_ID,

Clientes/Views/Contactos/Compromisos.cshtml
@model IEnumerable<Clientes.Models.ContactoModelView>

@{
    ViewBag.Title = "Compromisos";
}

<h2>Compromisos:: @ViewBag.Cliente</h2>

<p>
    @Html.ActionLink("Create New", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMENTARIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMPROMISO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_COMPROMISO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TIPO_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMENTARIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMPROMISO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_COMPROMISO)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Clientes/Views/Contactos/Contacto.cshtml
@model Clientes.Models.ContactoModelView
@{
    Layout = null;
    string panel = "success",titulo="Compromiso";
    if (String.IsNullOrEmpty(Model.COMPROMISO))
    {
        titulo = "Proximo Contacto";
        panel = "primary";
    }
}
<div>
    <h4>Cliente: @ViewBag.Ncli</h4>
    <hr />
    <div class="panel panel-@panel">
        <div class="panel-heading">
            <b>
                @titulo - 
                @if (!string.IsNullOrEmpty(Model.COMPROMISO))
                {
                   @Convert.ToDateTime(Model.FECHA_COMPROMISO).ToLongDateString()
                }
                else
                {
                   @Convert.ToDateTime(Model.FECHA_PROXIMO_CONTACTO).ToLongDateString()
                }
            </b>
        </div>
        <div class="panel-body">
            <ul class="list-group">
                <li class="list-group-item">Contacto:  <b>@Model.NOMBRE_CONTACTO</b></li>
                @if (!string.IsNullOrEmpty(Model.COMPROMISO))
                {
                    <li class="list-group-item">Compromiso: <b>@Model.COMPROMISO</b></li>
                }
                else
                {
                    <li class="list-group-item">Motivo proximo Contacto: <b>@Model.MOTIVO_PROXIMO_CONTACTO</b></li>
                    
                }
                <li class="list-group-item">Comentario: <b>@Model.COMENTARIO</b></li>
            </ul>
        </div>
    </div>
</div>


    @*<dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CONOCIMIENTO_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONOCIMIENTO_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOMBRE_CONTACTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO_CONTACTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COMENTARIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COMENTARIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_CONTACTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgregarCompromiso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgregarCompromiso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COMPROMISO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COMPROMISO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_COMPROMISO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_COMPROMISO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MOTIVO_PROXIMO_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MOTIVO_PROXIMO_CONTACTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_PROXIMO_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_PROXIMO_CONTACTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HORA_PROXIMO_CONTACTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HORA_PROXIMO_CONTACTO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

Clientes/Views/Contactos/Detail.cshtml
@model IEnumerable<Clientes.Models.ContactoModelView>

@{
    ViewBag.Title = "Contacto";
}

<h2>Cliente:: @ViewBag.Cliente</h2>

<p>
    <!--<a href="/Empresariales/Clientes/Contactos/Crear/@ViewBag.CL" class="btn btn-danger"><i class="glyphicon glyphicon-plus-sign"></i> Nuevo</a>-->
	@Html.ActionLink("Nuevo", "Crear","Contactos", new { id = ViewBag.CL }, new { @class = "btn btn-danger glyphicon glyphicon-plus-sign" })
</p>


<div class="contenedor row">
    <div class="col-md-6">
        <h3>Compromisos</h3>
        @foreach (var item in Model.Where(x => x.FECHA_PROXIMO_CONTACTO == null).OrderByDescending(x => x.FECHA_COMPROMISO))
        {
            <div class="panel panel-primary">
                <div class="panel-heading"><b>@Convert.ToDateTime(item.FECHA_COMPROMISO).ToLongDateString()</b></div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">Contacto:  <b>@item.NOMBRE_CONTACTO</b></li>
                        <li class="list-group-item">Compromiso: <b>@item.COMPROMISO</b></li>
                        <li class="list-group-item">Comentario: <b>@item.COMENTARIO</b></li>
                    </ul>
                </div>
            </div>
        }
    </div>

    <div class="col-md-6">
        <h3>Proximo Contacto</h3>
        @foreach (var item in Model.Where(x => x.FECHA_COMPROMISO == null).OrderByDescending(x => x.FECHA_PROXIMO_CONTACTO))
        {
            <div class="panel" style="border:1px solid #d6e9c6;">
                <div class="panel-heading" style="background:#5cb85c;color:#fff;"><b>@Convert.ToDateTime(item.FECHA_PROXIMO_CONTACTO).ToLongDateString()</b></div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">Contacto: <b>@item.NOMBRE_CONTACTO</b></li>
                        <li class="list-group-item">Motivo proximo Contacto: <b>@item.MOTIVO_PROXIMO_CONTACTO</b></li>
                        <li class="list-group-item">Comentario: <b>@item.COMENTARIO</b></li>
                    </ul>
                </div>
            </div>
        }
    </div>

</div>


@*<div class="compromisos">
    <h4  style="font-size:13px;" class="label label-success">Compromisos</h4>
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.COMENTARIO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.COMPROMISO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_COMPROMISO)
            </th>
        </tr>

        @foreach (var item in Model.Where(x=>x.FECHA_PROXIMO_CONTACTO==null).OrderByDescending(x=>x.FECHA_COMPROMISO))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NOMBRE_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TIPO_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.COMENTARIO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.COMPROMISO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_COMPROMISO)
                </td>
            </tr>
        }
    </table>
</div>

<div class="proximo">
    <h4 style="font-size:13px;" class="label label-primary">Contactos</h4>
    <table class="table table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.COMENTARIO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MOTIVO_PROXIMO_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_PROXIMO_CONTACTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HORA_PROXIMO_CONTACTO)
            </th>
           
        </tr>

        @foreach (var item in Model.Where(x=>x.FECHA_COMPROMISO==null).OrderByDescending(x=>x.FECHA_PROXIMO_CONTACTO))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NOMBRE_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TIPO_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.COMENTARIO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MOTIVO_PROXIMO_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_PROXIMO_CONTACTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HORA_PROXIMO_CONTACTO)
               
            </tr>
        }

    </table>
</div>*@

Clientes/Views/Contactos/Index.cshtml
@model IEnumerable<Clientes.Models.CONTACTO>

@{
    ViewBag.Title = "Index";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CONOCIMIENTO_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMENTARIO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CONOCIMIENTO_ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TIPO_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMENTARIO)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Detail", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Clientes/Views/Contactos/Proximo.cshtml
@model IEnumerable<Clientes.Models.ContactoModelView>

@{
    ViewBag.Title = "Proximo";
}

<h2>Proximo:: @ViewBag.Cliente</h2>

<p>
    @Html.ActionLink("Create New", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NOMBRE_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIPO_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.COMENTARIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MOTIVO_PROXIMO_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA_PROXIMO_CONTACTO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HORA_PROXIMO_CONTACTO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NOMBRE_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TIPO_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.COMENTARIO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MOTIVO_PROXIMO_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA_PROXIMO_CONTACTO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HORA_PROXIMO_CONTACTO)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>